#!/usr/bin/env python3
"""Project `docs/` into the knowledge read model, and guard it against drift (ADR-0024/0049).

**What this is.** The one-way build step from the governed estate to a relational projection: nodes and
typed edges, dropped and rebuilt rather than migrated. ADR-0024 calls the read model **disposable** and
ADR-0049 draws the consequence out loud — *migrations exist to preserve data, and a disposable
projection has none.* Its history is `docs/`, under git. That is deliberately **not** the ClickHouse
pattern: telemetry cannot be regenerated, so it earns migrations and a schema gate (ADR-0036).

**Why Python, and why it is not a lane breach.** ADR-0049 clause 2. The decisive argument is reuse:
`tools/verify.py` already parses every front-matter block, relation and rule ID in the estate, and it is
gate-tested (ADR-0042). A second parser in Rust would duplicate it and could **disagree with what the
gates consider valid** — the read model would then project a graph the gates never approved. So this
module *imports* that parser rather than reimplementing it. ENG-R10's "ingestion" is the per-event hot
path, which `crates/scm-ingest` owns; a build step over a few hundred files is not that.

**Why it opens no connection.** This slice emits SQL and checks the projection; it does not talk to a
server. Three reasons, in order of weight: there is no Postgres in this environment, so a connecting
version could not be tested and *an untested writer is worse than none*; the write identity is a
security decision that belongs with M4's deployment rather than with its projection; and it keeps the
repository at **zero runtime dependencies** for one more slice, which is a position worth spending
deliberately rather than by default (ADR-0050's audit).

**The drift guard, and why it is not tautological.** A projection generated from the estate in one pass
trivially "matches" the estate — comparing it to itself proves nothing. So the guard checks the counts
against an **independently declared** oracle: the `` ```dossier `` block that gate **G21** holds to the
estate (ADR-0052). Two numbers have to agree with a third party's declaration, which is a real
constraint: a parser that silently dropped a document would pass a self-comparison and fail this.

Usage:
    python3 tools/ingest.py --emit-sql          the full rebuild script on stdout
    python3 tools/ingest.py --check             the drift guard (exit 1 on drift)
    python3 tools/ingest.py --self-test         the projection's own invariants
    make verify-read-model                      the guard, as CI runs it

Exit status: 0 when the requested mode succeeded, 1 on drift or a failed self-test.
"""

from __future__ import annotations

import argparse
import os
import re
import subprocess
import sys

sys.path.insert(0, os.path.dirname(os.path.abspath(__file__)))

from verify import (  # noqa: E402  — the import IS the design decision (ADR-0049 clause 2)
    DOCS_DIR,
    DOSSIER,
    DOSSIER_FENCE,
    RELATION_TYPES,
    is_allowlisted,
    parse_front_matter,
    tier_of,
)

# The projection's shape. Two tables and nothing else: a node carries what a reader selects on, an edge
# carries the typed relation. No computed column, no denormalized rollup — anything derived belongs in
# the query, because the projection is rebuilt and a derived column would have to be rebuilt correctly
# too. `tier` is the exception and it is not derived from the row: it comes from the document's *path*
# (knowledge-architecture §2), which SQL cannot see.
SCHEMA = """\
-- Generated by tools/ingest.py from docs/ — DO NOT EDIT, DO NOT MIGRATE.
-- ADR-0024: the knowledge read model is dropped and rebuilt, never hand-edited.
-- ADR-0049: a disposable projection has no data to preserve, so it has no migrations.
-- Its history is docs/, under git. Regenerate with `python3 tools/ingest.py --emit-sql`.

BEGIN;

DROP TABLE IF EXISTS knowledge_edge;
DROP TABLE IF EXISTS knowledge_node;

CREATE TABLE knowledge_node (
    id       text PRIMARY KEY,
    path     text NOT NULL UNIQUE,
    title    text NOT NULL,
    type     text NOT NULL,
    owner    text NOT NULL,
    status   text NOT NULL,
    since    date NOT NULL,
    updated  date NOT NULL,
    tier     smallint          -- NULL for meta/non-authority (00-governance, program, standards)
);

CREATE TABLE knowledge_edge (
    source_id  text NOT NULL REFERENCES knowledge_node(id),
    relation   text NOT NULL,
    target_id  text NOT NULL,   -- NOT a foreign key: `governance-root` is virtual, it has no row
    PRIMARY KEY (source_id, relation, target_id)
);

CREATE INDEX knowledge_edge_target ON knowledge_edge (target_id, relation);
CREATE INDEX knowledge_node_type ON knowledge_node (type, status);
"""


def sql_literal(value: str) -> str:
    """A single-quoted SQL string with quotes doubled.

    Values are escaped rather than parameterized because this emits a *script*, not a statement to
    execute — there is no connection to bind against. It is the only place in this file where a value
    meets SQL, which is why it is one function and not an f-string at each call site.
    """
    return "'" + value.replace("'", "''") + "'"


def collect() -> tuple[list[dict], list[tuple[str, str, str]], list[str]]:
    """(nodes, edges, problems) over the governed tree, using verify.py's own parser."""
    root = subprocess.run(["git", "rev-parse", "--show-toplevel"],
                          capture_output=True, text=True).stdout.strip()
    if not root:
        return [], [], ["not a git repository — the projection reads the tracked tree"]
    os.chdir(root)
    tracked = subprocess.run(["git", "ls-files"], capture_output=True, text=True).stdout.splitlines()

    nodes, edges, problems, seen = [], [], [], {}
    for path in sorted(tracked):
        if not path.endswith(".md") or is_allowlisted(path):
            continue
        if not path.startswith(f"{DOCS_DIR}/"):
            continue
        try:
            text = open(path, encoding="utf-8").read()
        except OSError as exc:
            problems.append(f"{path}: unreadable ({exc})")
            continue
        meta, err = parse_front_matter(text)
        if err:
            # G1/G2 own this failure; the projection refuses the row rather than inventing one.
            problems.append(f"{path}: {err}")
            continue
        doc_id = meta.get("id", "")
        if not doc_id:
            problems.append(f"{path}: no id")
            continue
        if doc_id in seen:
            problems.append(f"duplicate id '{doc_id}' in {path} and {seen[doc_id]} — the primary key "
                            f"would reject one of them, and which one is arbitrary")
            continue
        seen[doc_id] = path
        nodes.append({
            "id": doc_id,
            "path": path,
            "title": meta.get("title", ""),
            "type": meta.get("type", ""),
            "owner": meta.get("owner", ""),
            "status": meta.get("status", ""),
            "since": meta.get("since", ""),
            "updated": meta.get("updated", ""),
            "tier": tier_of(path, meta.get("type", "")),
        })
        for relation, target in meta["relations"]:
            if relation not in RELATION_TYPES:
                problems.append(f"{path}: relation '{relation}' outside the vocabulary")
                continue
            edges.append((doc_id, relation, target))
    return nodes, edges, problems


def emit_sql(nodes: list[dict], edges: list[tuple[str, str, str]]) -> str:
    out = [SCHEMA]
    for node in nodes:
        tier = "NULL" if node["tier"] is None else str(node["tier"])
        out.append(
            "INSERT INTO knowledge_node (id, path, title, type, owner, status, since, updated, tier) "
            f"VALUES ({sql_literal(node['id'])}, {sql_literal(node['path'])}, "
            f"{sql_literal(node['title'])}, {sql_literal(node['type'])}, "
            f"{sql_literal(node['owner'])}, {sql_literal(node['status'])}, "
            f"{sql_literal(node['since'])}, {sql_literal(node['updated'])}, {tier});"
        )
    out.append("")
    for source, relation, target in edges:
        out.append(
            "INSERT INTO knowledge_edge (source_id, relation, target_id) "
            f"VALUES ({sql_literal(source)}, {sql_literal(relation)}, {sql_literal(target)});"
        )
    out.append("\nCOMMIT;")
    return "\n".join(out) + "\n"


DOSSIER_LINE = re.compile(r"^(\S+)\s+(\S+)$", re.M)


def declared_facts() -> dict[str, str]:
    """The dossier's counted facts — the projection's independent oracle (ADR-0052)."""
    try:
        fence = DOSSIER_FENCE.search(open(DOSSIER, encoding="utf-8").read())
    except OSError:
        return {}
    if not fence:
        return {}
    return {m.group(1): m.group(2) for m in DOSSIER_LINE.finditer(fence.group(1))
            if not m.group(1).startswith("#")}


def check(nodes: list[dict], edges: list[tuple[str, str, str]], problems: list[str]) -> int:
    failures = list(problems)

    facts = declared_facts()
    if not facts:
        failures.append(f"{DOSSIER}: no dossier block to check the projection against — the guard's "
                        f"whole value is that its oracle is declared elsewhere")
    else:
        for key, actual in (("governed-docs", len(nodes)), ("graph-edges", len(edges))):
            want = facts.get(key)
            if want is None:
                failures.append(f"{DOSSIER} declares no '{key}'")
            elif want != str(actual):
                failures.append(
                    f"projected {actual} {key.replace('-', ' ')} but the dossier declares {want}. "
                    f"One of the two is wrong and neither is authoritative over the other — G21 holds "
                    f"the dossier to the estate, so a disagreement here means this parser and "
                    f"verify.py have diverged, which is the failure ADR-0049 chose Python to prevent")

    ids = {node["id"] for node in nodes}
    # `governance-root` is the apex and has no document, so it is a legitimate target with no row.
    # That is why knowledge_edge.target_id is not a foreign key, and the exemption is named here
    # rather than left as a silent skip.
    virtual = {"governance-root"}
    for source, relation, target in edges:
        if target not in ids and target.split("#")[0] not in virtual:
            failures.append(f"edge {source} --{relation}--> {target} points at no projected node; "
                            f"the read model would carry a dangling reference G4 does not allow")

    empty = [node["id"] for node in nodes
             if not all(node[field] for field in ("title", "type", "owner", "status"))]
    for doc_id in empty:
        failures.append(f"node '{doc_id}' would project a NOT NULL column empty")

    if failures:
        print("RED — the knowledge read model has drifted from docs/")
        for failure in failures:
            print(f"  - {failure}")
        return 1
    print(f"GREEN — projection matches the estate: {len(nodes)} nodes, {len(edges)} edges, "
          f"checked against the dossier's declared counts")
    return 0


def self_test(nodes: list[dict], edges: list[tuple[str, str, str]]) -> int:
    """Invariants of the projection itself, independent of how many documents exist."""
    checks: list[tuple[str, bool, str]] = []
    by_id = {node["id"]: node for node in nodes}

    checks.append(("the apex is reachable and has no row of its own",
                   "governance-root" not in by_id
                   and any(t == "governance-root" for _s, _r, t in edges),
                   "the root contract carries no front matter, so it must appear only as a target"))

    checks.append(("every node has a unique path",
                   len({node["path"] for node in nodes}) == len(nodes),
                   "path carries a UNIQUE constraint, so a collision would abort the rebuild"))

    checks.append(("edges are unique on the primary key",
                   len({(s, r, t) for s, r, t in edges}) == len(edges),
                   "(source, relation, target) is the primary key; a duplicate would abort the load"))

    quoted = [node for node in nodes if "'" in node["title"]]
    checks.append((f"titles with an apostrophe survive escaping ({len(quoted)} present)",
                   all("''" in emit_sql([node], []) for node in quoted) if quoted else True,
                   "an unescaped apostrophe is both a broken rebuild and an injection shape"))

    checks.append(("tier comes from the path, and meta tiers are NULL rather than 0",
                   all(node["tier"] is None or 1 <= node["tier"] <= 6 for node in nodes),
                   "0 would sort above the contract; NULL says 'not on the ladder' (§2)"))

    ok = True
    for label, passed, why in checks:
        print(f"  {'ok  ' if passed else 'FAIL'}  {label}")
        if not passed:
            ok = False
            print(f"        {why}")
    print(f"\n{'GREEN' if ok else 'RED'} — {len(checks)} projection invariants")
    return 0 if ok else 1


def main() -> int:
    parser = argparse.ArgumentParser(description=__doc__.split("\n")[0])
    mode = parser.add_mutually_exclusive_group(required=True)
    mode.add_argument("--emit-sql", action="store_true", help="write the rebuild script to stdout")
    mode.add_argument("--check", action="store_true", help="the drift guard")
    mode.add_argument("--self-test", action="store_true", help="the projection's own invariants")
    args = parser.parse_args()

    nodes, edges, problems = collect()
    if args.emit_sql:
        if problems:
            for problem in problems:
                print(f"refusing to emit: {problem}", file=sys.stderr)
            return 1
        sys.stdout.write(emit_sql(nodes, edges))
        return 0
    if args.check:
        return check(nodes, edges, problems)
    return self_test(nodes, edges)


if __name__ == "__main__":
    sys.exit(main())
